sudo: false

language: go

install:
  - go get -v -t -d ./...
  - go build -v
  - go install github.com/onsi/ginkgo/ginkgo

script:
  - go tool vet -composites=false $(ls -d */ | grep -v Godeps)
  - go tool vet -composites=false *.go
  - ginkgo -r -race -randomizeAllSpecs

branches:
  only:
  - master
