---
resources:
- name: garagepi
  type: git
  source:
    uri: git@github.com:robdimsdale/garagepi
    branch: master
    private_key: {{private-key}}

jobs:
- name: unit-tests
  plan:
  - get: garagepi
    trigger: true
  - task: unit-tests
    file: garagepi/scripts/ci/unit-tests.yml
