---
resources:
- name: garagepi
  type: git
  source:
    uri: git@github.com:robdimsdale/garagepi
    branch: develop
    private_key: {{private-key}}

- name: garagepi-master
  type: git
  source:
    uri: git@github.com:robdimsdale/garagepi
    branch: master
    private_key: {{private-key}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-url}}

- name: version
  type: semver
  source:
    bucket: garagepi-releases
    key: current-version
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: candidate-release-arm
  type: s3
  source:
    bucket: garagepi-releases
    regexp: garagepi-arm-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: candidate-release-linux
  type: s3
  source:
    bucket: garagepi-releases
    regexp: garagepi-linux-(.*)
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

- name: docker-garagepi-1.4
  type: docker-image
  source:
    repository: robdimsdale/garagepi-1.4
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: docker-garagepi-1.5
  type: docker-image
  source:
    repository: robdimsdale/garagepi-1.5
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

- name: docker-garagepi-cross-compile
  type: docker-image
  source:
    repository: robdimsdale/garagepi-cross-compile
    username: {{docker-username}}
    password: {{docker-password}}
    email: {{docker-email}}

jobs:
- name: golang-1.4
  public: false
  plan:
  - get: garagepi
    trigger: true
  - task: unit-integration-tests
    file: garagepi/scripts/ci/golang-1.4/unit-integration-tests.yml
    on_success:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-4-slack-success-text}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-4-slack-failure-text}}

- name: golang-1.5
  public: false
  plan:
  - get: garagepi
    trigger: true
  - task: unit-integration-tests
    file: garagepi/scripts/ci/golang-1.5/unit-integration-tests.yml
    on_success:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-5-slack-success-text}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-5-slack-failure-text}}

- name: rc
  public: false
  serial_groups: [version]
  plan:
  - aggregate:
    - get: garagepi
      trigger: true
      passed: [golang-1.4,golang-1.5]
    - get: version
      params: {pre: rc}
  - aggregate:
    - task: create-candidate-release-arm
      file: garagepi/scripts/ci/create-candidate-release-arm.yml
    - task: create-candidate-release-linux
      file: garagepi/scripts/ci/create-candidate-release-linux.yml
  - aggregate:
    - put: candidate-release-arm
      params: {from: create-candidate-release-arm/garagepi-arm-(.*)}
    - put: candidate-release-linux
      params: {from: create-candidate-release-linux/garagepi-linux-(.*)}
  - put: version
    params: {file: version/number}

- name: smoke-tests
  public: false
  plan:
  - aggregate:
    - get: garagepi
      trigger: true
      passed: [rc]
    - get: version
      passed: [rc]
    - get: candidate-release-arm
      passed: [rc]
    - get: candidate-release-linux
      passed: [rc]
  - task: smoke-tests-linux
    file: garagepi/scripts/ci/candidate-release-linux-smoke-tests.yml

- name: shipit
  serial_groups: [version]
  public: false
  plan:
  - aggregate:
    - get: garagepi
      passed: [smoke-tests]
      params: {fetch: [master]}
    - get: candidate-release-arm
      passed: [smoke-tests]
    - get: candidate-release-linux
      passed: [smoke-tests]
    - get: version
      passed: [smoke-tests]
      params: {bump: final}
  - aggregate:
    - task: finalize-candidate-release-arm
      file: garagepi/scripts/ci/finalize-candidate-release-arm.yml
    - task: finalize-candidate-release-linux
      file: garagepi/scripts/ci/finalizee-candidate-release-linux.yml
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: garagepi-master
      params:
        repository: garagepi
        tag: version/number
        tag_prefix: v
    - put: candidate-release-arm
      params: {from: finalize-candidate-release-arm/garagepi-arm-(.*)}
    - put: candidate-release-linux
      params: {from: finalize-candidate-release-linux/garagepi-linux-(.*)}

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major}
  - put: version
    params: {file: version/number}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/number}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch}
    trigger: true
  - put: version
    params: {file: version/number}

- name: docker-garagepi-1.4
  plan:
  - get: garagepi
    trigger: true
  - put: docker-garagepi-1.4
    params:
      build: garagepi/scripts/ci/golang-1.4

- name: docker-garagepi-1.5
  plan:
  - get: garagepi
    trigger: true
  - put: docker-garagepi-1.5
    params:
      build: garagepi/scripts/ci/golang-1.5

- name: docker-garagepi-cross-compile
  plan:
  - get: garagepi
    trigger: true
  - put: docker-garagepi-cross-compile
    params:
      build: garagepi/scripts/ci/cross-compile

groups:
- name: garagepi
  jobs:
  - golang-1.4
  - golang-1.5
  - rc
  - smoke-tests
  - shipit
  - major
  - minor
  - patch
- name: images
  jobs:
  - docker-garagepi-1.4
  - docker-garagepi-1.5
  - docker-garagepi-cross-compile
