---
resources:
- name: garagepi
  type: git
  source:
    uri: git@github.com:robdimsdale/garagepi
    branch: develop
    private_key: {{private-key}}

- name: garagepi-master
  type: git
  source:
    uri: git@github.com:robdimsdale/garagepi
    branch: master
    private_key: {{private-key}}

- name: slack-alert
  type: slack-notification
  source:
    url: {{slack-url}}

- name: version
  type: semver
  source:
    bucket: garagepi-releases
    key: current-version
    access_key_id: {{pipeline-bucket-access-key}}
    secret_access_key: {{pipeline-bucket-secret-key}}

jobs:
- name: golang-1.2
  public: false
  plan:
  - get: garagepi
    trigger: true
  - task: unit-integration-tests
    file: garagepi/scripts/ci/golang-1.2/unit-integration-tests.yml
    on_success:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-2-slack-success-text}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-2-slack-failure-text}}
- name: golang-1.3
  public: false
  plan:
  - get: garagepi
    trigger: true
  - task: unit-integration-tests
    file: garagepi/scripts/ci/golang-1.3/unit-integration-tests.yml
    on_success:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-3-slack-success-text}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-3-slack-failure-text}}
- name: golang-1.4
  public: false
  plan:
  - get: garagepi
    trigger: true
  - task: unit-integration-tests
    file: garagepi/scripts/ci/golang-1.4/unit-integration-tests.yml
    on_success:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-4-slack-success-text}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-4-slack-failure-text}}
- name: golang-1.5
  public: false
  plan:
  - get: garagepi
    trigger: true
  - task: unit-integration-tests
    file: garagepi/scripts/ci/golang-1.5/unit-integration-tests.yml
    on_success:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-5-slack-success-text}}
    on_failure:
      put: slack-alert
      params:
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
        channel: {{slack-channel}}
        text: {{v1-5-slack-failure-text}}

- name: shipit
  public: false
  serial: true
  plan:
  - aggregate:
    - get: garagepi
      passed: [golang-1.2,golang-1.3,golang-1.4,golang-1.5]
      params: {fetch: [master]}
    - get: version
      params: {bump: minor}
  - aggregate:
    - put: version
      params: {file: version/number}
    - put: garagepi-master
      params:
        repository: garagepi
        tag: version/number
        tag_prefix: v
